version: 2.1
jobs:
  build:
    working_directory: ~/stac
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: init_submodules
          command: git submodule update --init --recursive
      - run:
          name: install
          command: npm install
      - run:
          name: validate
          command: npm run check